language: node_js
node_js:
  - "stable"

# Build Doc site
cache:
  yarn: true

# Different ways to have it trigger on conditions 
# script:
#     - git config --global user.name "${GH_NAME}"
#     - git config --global user.email "${GH_EMAIL}"
#     - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
#     - cd ./doc && npm install && GIT_USER="${GH_NAME}" docusaurus deploy

# Overall builds only on branches not master
if: branch != master
script:
    - git config --global user.name "${GH_NAME}"
    - git config --global user.email "${GH_EMAIL}"
    - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
    - cd ./docs && npm install && GIT_USER="${GH_NAME}" docusaurus deploy

# Overall builds only on master and PR into master
# if: branch = master
# script:
#     - git config --global user.name "${GH_NAME}"
#     - git config --global user.email "${GH_EMAIL}"
#     - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
#     - cd ./docs && npm install && GIT_USER="${GH_NAME}" docusaurus deploy

# Job is built only if master
# jobs:
#   include:
#     - # require the branch name to be master (note for PRs this is the base branch name)
#       if: branch = master
#       script:
#         - git config --global user.name "${GH_NAME}"
#         - git config --global user.email "${GH_EMAIL}"
#         - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
#         - cd ./docs && npm install && GIT_USER="${GH_NAME}" docusaurus deploy