site_name: Coastal Image Labeler Docs
repo_url: https://github.com/UNCG-DAISY/Coastal-Image-Labeler

nav:
    - Home: index.md
    - Code of Conduct: code_of_conduct.md
    - Code Documentation:
      - Overview: code_documentation/overview.md
      - 1 - Packages: code_documentation/packages.md
      - 2 - Project Structure: code_documentation/project_structure.md
      - 3 - Auth0: code_documentation/auth0.md
      - 4 - Data export: code_documentation/data_export.md
      - 5 - Maintenance: code_documentation/maintenance.md
      - 6 - Extending:
        - Add New Question Set: code_documentation/extensions/form/question_set.md
    - User Documentation:
      - Overview: user_documentation/overview.md
      - Image Tagging Process: user_documentation/tagging_process.md
      - Question Sets:
        - Storm: user_documentation/question_sets/storm.md
        - Dune Collision: user_documentation/question_sets/collision.md

theme:
  logo: img/logo.svg
  name: 'material'
  palette:
    scheme: slate
    primary: 'light green'
    accent: 'light green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

markdown_extensions:
  - codehilite:
      # linenums: false
      # use_pygments: true
      noclasses: true
      pygments_style: monokai
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tilde


extra_css:
  - stylesheets/custom.css
