site_name: CIL Dashboard
repo_url: https://github.com/UNCG-DAISY/Coastal-Image-Labeler

nav:
    - Home: index.md
    - Code of Conduct: code_of_conduct.md
    - Code Documentation: 
      - Overview: code_documentation/overview.md
      - 1 - Packages: code_documentation/packages.md
      - 2 - Project Structure: code_documentation/project_structure.md
      - 3 - Auth0: code_documentation/auth0.md
      - 4 - Data export: code_documentation/data_export.md
      - 5 - Maintenance: code_documentation/maintenance.md
      - 6 - Extending:
        - Add Radio Buttons: code_documentation/extensions/form/radiobutton.md
        - Add Checkbox Buttons: code_documentation/extensions/form/checkboxButton.md
    - User Documentation: 
      - Overview: user_documentation/overview.md
      - Image Tagging Process: user_documentation/tagging_process.md
      - Examples:
        - Storm Impact: user_documentation/examples/storm_impact.md

theme:
  logo: images/logo.svg
  name: 'material'
  palette:
    scheme: slate
    primary: 'light green'
    accent: 'light green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

markdown_extensions:
  - codehilite:
      linenums: true
      guess_lang: False
      use_pygments: True
      pygments_style: fruity
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tilde


extra_css:
  - stylesheets/custom.css

